# Generated by Django 4.1.5 on 2023-01-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0003_collection_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='magic.collection'),
        ),
    ]
